name: Deploy to FTP

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest  # Рекомендую использовать ubuntu вместо macos для экономии времени

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run generate  # или npm run build для SSR

      - name: Verify output
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -R ./.output/public/ || echo "Trying alternative location..."
          ls -R ./dist/ || echo "No output directory found"

      - name: FTP Deploy
        if: success()
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./.output/public/  # или ./dist/ если файлы там
          server-dir: /