name: Deploy to FTP

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v2.0.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run generate || (echo "Build failed" && exit 1)
          echo "Build completed"

      - name: Verify build output
        run: |
          echo "Checking build output directory..."
          ls -la .output/
          ls -la .output/public/ || echo "No public directory"
          echo "Directory tree:"
          find .output/ -type d

      - name: FTP Deploy
        if: success()
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .output/public/
          server-dir: /
          exclude: '**/.git*'