on:
  push:
  workflow_dispatch:

name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate with debug
        run: |
            npm run generate
            echo "Build finished, checking output..."
            ls -la .output || echo "No output dir"
            ls -la .output/public || echo "No public dir"
            ls -la .dist || echo "No dist dir"

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .output/public/
          server-dir: /
          dangerous-clean-slate: true